apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-tester
  template:
    metadata:
      labels:
        app: app-tester
    spec:
      containers:
        - name: app-tester
          image: nowl2112/app-tester
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
