apiVersion: v1
kind: Service
metadata:
  name: fsdp-service
spec:
  selector:
    app: fsdp
  ports:
    - protocol: TCP
      port: 80           # Exposed port to the outside world
      targetPort: 3000    # Port the application is running on
  type: LoadBalancer
